-- ==============================================================================
-- ORACLE PL/SQL DDL & GOVERNANCE PACKAGE SCRIPT
-- Script Name : supplier_risk_governance_pkg.sql
-- Description : Audit Logging & Automated Governance Workflow Engine for APEX / ORDS
-- Author      : Oracle Principal Database Architect
-- Date        : 2026-09-24
-- ==============================================================================

--------------------------------------------------------------------------------
-- 1. DDL: Audit Log Table & Sequence
--------------------------------------------------------------------------------
CREATE SEQUENCE ai_audit_seq START WITH 10001 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE TABLE ai_financial_audit_log (
    log_id              NUMBER DEFAULT ai_audit_seq.NEXTVAL PRIMARY KEY,
    vendor_id           NUMBER NOT NULL,
    risk_rating         VARCHAR2(50) NOT NULL,
    action_recommended  VARCHAR2(100) NOT NULL,
    financial_score     NUMBER(3),
    scm_resilience_score NUMBER(3),
    sox_compliance_flag VARCHAR2(5),
    agent_reasoning     CLOB,
    created_by          VARCHAR2(255) DEFAULT COALESCE(SYS_CONTEXT('APEX$SESSION', 'APP_USER'), USER),
    creation_date       DATE DEFAULT SYSDATE
);

COMMENT ON TABLE ai_financial_audit_log IS 'Audit log storing AI supplier diligence evaluations for SOX internal controls compliance.';
COMMENT ON COLUMN ai_financial_audit_log.LOG_ID IS 'Surrogate primary key generated by ai_audit_seq.';
COMMENT ON COLUMN ai_financial_audit_log.VENDOR_ID IS 'PO Supplier internal ID (PO_VENDORS.VENDOR_ID).';
COMMENT ON COLUMN ai_financial_audit_log.RISK_RATING IS 'Evaluated supplier risk rating (LOW, MEDIUM, HIGH, CRITICAL).';
COMMENT ON COLUMN ai_financial_audit_log.ACTION_RECOMMENDED IS 'Recommended action (APPROVE, HOLD_PO_PAYOUTS, REROUTE_SUPPLIER_ALLOCATION, HUMAN_REVIEW_REQUIRED).';

--------------------------------------------------------------------------------
-- 2. PL/SQL Package Specification: PKG_SUPPLIER_RISK_GOVERNANCE
--------------------------------------------------------------------------------
CREATE OR REPLACE PACKAGE pkg_supplier_risk_governance AS

    -- Invokes OCI Function / Gemini API endpoint and executes audit actions
    PROCEDURE process_supplier_audit (
        p_supplier_payload CLOB,
        p_oci_endpoint_url VARCHAR2 DEFAULT NULL
    );

    -- Helper procedure to record audit decision and apply ERP holds
    PROCEDURE execute_governance_action (
        p_vendor_id        IN NUMBER,
        p_risk_rating      IN VARCHAR2,
        p_action           IN VARCHAR2,
        p_financial_score  IN NUMBER,
        p_scm_score        IN NUMBER,
        p_sox_flag         IN VARCHAR2,
        p_justification    IN CLOB
    );

END pkg_supplier_risk_governance;
/

--------------------------------------------------------------------------------
-- 3. PL/SQL Package Body: PKG_SUPPLIER_RISK_GOVERNANCE
--------------------------------------------------------------------------------
CREATE OR REPLACE PACKAGE BODY pkg_supplier_risk_governance AS

    PROCEDURE process_supplier_audit (
        p_supplier_payload CLOB,
        p_oci_endpoint_url VARCHAR2 DEFAULT NULL
    ) IS
        v_gemini_response  CLOB;
        v_endpoint         VARCHAR2(2000);
        
        -- Parsed JSON variables
        v_vendor_id        NUMBER;
        v_action           VARCHAR2(100);
        v_risk_rating      VARCHAR2(50);
        v_fin_score        NUMBER;
        v_scm_score        NUMBER;
        v_sox_bool         BOOLEAN;
        v_sox_str          VARCHAR2(5);
        v_justification    CLOB;
    BEGIN
        v_endpoint := NVL(p_oci_endpoint_url, 'https://<oci-function-endpoint>/parse-supplier-risk');
        
        -- 1. Call OCI Function / Gemini API Endpoint via APEX_WEB_SERVICE
        APEX_WEB_SERVICE.g_request_headers(1).name  := 'Content-Type';
        APEX_WEB_SERVICE.g_request_headers(1).value := 'application/json';

        v_gemini_response := APEX_WEB_SERVICE.MAKE_REST_REQUEST(
            p_url         => v_endpoint,
            p_http_method => 'POST',
            p_body        => p_supplier_payload
        );

        -- 2. Parse JSON Response using APEX_JSON
        APEX_JSON.PARSE(v_gemini_response);
        v_vendor_id     := APEX_JSON.GET_NUMBER('vendor_id');
        v_action        := APEX_JSON.GET_VARCHAR2('recommended_action');
        v_risk_rating   := APEX_JSON.GET_VARCHAR2('overall_risk_rating');
        v_fin_score     := APEX_JSON.GET_NUMBER('financial_risk_score');
        v_scm_score     := APEX_JSON.GET_NUMBER('supply_chain_resilience_score');
        v_sox_bool      := APEX_JSON.GET_BOOLEAN('sox_compliance_flag');
        v_justification := APEX_JSON.GET_CLOB('justification');
        
        v_sox_str := CASE WHEN v_sox_bool THEN 'TRUE' ELSE 'FALSE' END;

        -- 3. Execute Logging & Governance Workflows
        execute_governance_action(
            p_vendor_id        => v_vendor_id,
            p_risk_rating      => v_risk_rating,
            p_action           => v_action,
            p_financial_score  => v_fin_score,
            p_scm_score        => v_scm_score,
            p_sox_flag         => v_sox_str,
            p_justification    => v_justification
        );

    EXCEPTION
        WHEN OTHERS THEN
            APEX_DEBUG.ERROR('Error in PKG_SUPPLIER_RISK_GOVERNANCE.process_supplier_audit: ' || SQLERRM);
            RAISE;
    END process_supplier_audit;

    PROCEDURE execute_governance_action (
        p_vendor_id        IN NUMBER,
        p_risk_rating      IN VARCHAR2,
        p_action           IN VARCHAR2,
        p_financial_score  IN NUMBER,
        p_scm_score        IN NUMBER,
        p_sox_flag         IN VARCHAR2,
        p_justification    IN CLOB
    ) IS
        v_app_user VARCHAR2(255);
    BEGIN
        v_app_user := COALESCE(SYS_CONTEXT('APEX$SESSION', 'APP_USER'), USER);

        -- 1. Insert SOX Audit Log Record
        INSERT INTO ai_financial_audit_log (
            log_id,
            vendor_id,
            risk_rating,
            action_recommended,
            financial_score,
            scm_resilience_score,
            sox_compliance_flag,
            agent_reasoning,
            created_by,
            creation_date
        ) VALUES (
            ai_audit_seq.NEXTVAL,
            p_vendor_id,
            p_risk_rating,
            p_action,
            p_financial_score,
            p_scm_score,
            p_sox_flag,
            p_justification,
            v_app_user,
            SYSDATE
        );

        -- 2. Execute Automated Workflow Actions
        IF p_action = 'HOLD_PO_PAYOUTS' THEN
            -- Apply PO hold status in Oracle Fusion / EBS
            UPDATE po_headers_all
            SET authorization_status = 'ON_HOLD',
                note_to_vendor       = 'Automated Governance Hold: Supplier liquidity risk threshold exceeded.'
            WHERE vendor_id = p_vendor_id 
              AND authorization_status = 'APPROVED';

        ELSIF p_action IN ('REROUTE_SUPPLIER_ALLOCATION', 'HUMAN_REVIEW_REQUIRED') THEN
            -- Trigger APEX / BPM Approval Task for SCM Procurement Manager
            BEGIN
                APEX_APPROVAL.CREATE_TASK(
                    p_application_id     => NVL(V('APP_ID'), 100),
                    p_task_def_static_id => 'SUPPLIER_RISK_ESCALATION',
                    p_subject            => 'URGENT: High Risk Supplier Review - Vendor ID ' || p_vendor_id,
                    p_param_values       => APEX_APPROVAL.T_TASK_PARAMETER(
                        1 => APEX_APPROVAL.T_TASK_PARAMETER_REC('VENDOR_ID', TO_CHAR(p_vendor_id)),
                        2 => APEX_APPROVAL.T_TASK_PARAMETER_REC('RISK_SUMMARY', SUBSTR(DBMS_LOB.SUBSTR(p_justification, 4000, 1), 1, 4000))
                    )
                );
            EXCEPTION
                WHEN OTHERS THEN
                    -- Fallback logging if APEX_APPROVAL task definition is not initialized
                    APEX_DEBUG.WARN('APEX_APPROVAL task creation skipped: ' || SQLERRM);
            END;
        END IF;

        COMMIT;
    END execute_governance_action;

END pkg_supplier_risk_governance;
/
